server:
  port: 8181
spring:
  application:
    name: USER-MGMT-API
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/XE
    username: RPH
    password: admin
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: bowbowtags@gmail.com
    password: rlyyfcfmzvwtonbd
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
app:
  messages:
    welcomeMsg: Welcome to our World !!
    invalidCredentials: Invalid Credentials
    accLocked: Your Account is Locked
    userRegSuccess: Please check your email for unlocking your account
    userRegFail : Failed to Register
    unlockAccEmailSub: Registration Success || Technology
    unlockAccEmailBodyFile: UNLOCK-ACC-EMAIL-BODY-TEMPLATE.txt
    recoverPwdEmailBodyFile: RECOVER-PASSWORD-EMAIL-BODY-TEMPLATE.txt
    recoverPwdEmailSub: Forgot Password || Technology
